##################################################
# VisualizerService_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from VisualizerService_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class VisualizerService(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions name=\"VisualizerService\" targetNamespace=\"http://service.apollo.pitt.edu/visualizerservice/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:tns=\"http://service.apollo.pitt.edu/visualizerservice/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">
	<wsdl:types>
		<xsd:schema targetNamespace=\"http://service.apollo.pitt.edu/visualizerservice/\" xmlns:apollo=\"http://types.apollo.pitt.edu/\">
			<xsd:import namespace=\"http://types.apollo.pitt.edu/\" schemaLocation=\"apollo-types.xsd\">
			</xsd:import>
			<xsd:element name=\"run\">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name=\"visualizerConfiguration\" type=\"apollo:VisualizerConfiguration\"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name=\"runResponse\">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name=\"runId\" type=\"apollo:RunId\"/>
						<xsd:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"visualizerOutputResource\" type=\"apollo:VisualizerOutputResource\">
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name=\"getRunStatus\">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name=\"runId\" type=\"apollo:RunId\"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name=\"getRunStatusResponse\">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name=\"runStatus\" type=\"apollo:RunStatus\"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name=\"runRequest\">
		<wsdl:part element=\"tns:run\" name=\"parameters\"/>
	</wsdl:message>
	<wsdl:message name=\"runResponse\">
		<wsdl:part element=\"tns:runResponse\" name=\"parameters\"/>
	</wsdl:message>
	<wsdl:message name=\"getRunStatusRequest\">
		<wsdl:part element=\"tns:getRunStatus\" name=\"parameters\"/>
	</wsdl:message>
	<wsdl:message name=\"getRunStatusResponse\">
		<wsdl:part element=\"tns:getRunStatusResponse\" name=\"parameters\"/>
	</wsdl:message>
	<wsdl:portType name=\"VisualizerServiceEI\">
		<wsdl:operation name=\"run\">
			<wsdl:input message=\"tns:runRequest\"/>
			<wsdl:output message=\"tns:runResponse\"/>
		</wsdl:operation>
		<wsdl:operation name=\"getRunStatus\">
			<wsdl:input message=\"tns:getRunStatusRequest\"/>
			<wsdl:output message=\"tns:getRunStatusResponse\"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name=\"VisualizerServiceBinding\" type=\"tns:VisualizerServiceEI\">
		<soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
		<wsdl:operation name=\"run\">
			<soap:operation soapAction=\"http://service.apollo.pitt.edu/visualizerservice/run\"/>
			<wsdl:input>
				<soap:body use=\"literal\"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use=\"literal\"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name=\"getRunStatus\">
			<soap:operation soapAction=\"http://service.apollo.pitt.edu/visualizerservice/getRunStatus\"/>
			<wsdl:input>
				<soap:body use=\"literal\"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use=\"literal\"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name=\"VisualizerService\">
		<wsdl:port binding=\"tns:VisualizerServiceBinding\" name=\"VisualizerServiceEndpoint\">
			<soap:address location=\"http://localhost:8080/visualizerservice/services/visualizerservice\"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/visualizerservice/services/visualizerservice', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_run(self, ps):
        self.request = ps.Parse(runRequest.typecode)
        return runResponse()

    soapAction['http://service.apollo.pitt.edu/visualizerservice/run'] = 'soap_run'
    root[(runRequest.typecode.nspname,runRequest.typecode.pname)] = 'soap_run'

    def soap_getRunStatus(self, ps):
        self.request = ps.Parse(getRunStatusRequest.typecode)
        return getRunStatusResponse()

    soapAction['http://service.apollo.pitt.edu/visualizerservice/getRunStatus'] = 'soap_getRunStatus'
    root[(getRunStatusRequest.typecode.nspname,getRunStatusRequest.typecode.pname)] = 'soap_getRunStatus'

