//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 06:45:13 PM EST 
//


package edu.pitt.rods.research.apollo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modeltype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelID", propOrder = {
    "groupid",
    "modelid",
    "modeltype",
    "version"
})
public class ModelID {

    @XmlElement(required = true)
    protected String groupid;
    @XmlElement(required = true)
    protected String modelid;
    @XmlElement(required = true)
    protected String modeltype;
    @XmlElement(required = true)
    protected String version;

    /**
     * Gets the value of the groupid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * Sets the value of the groupid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupid(String value) {
        this.groupid = value;
    }

    /**
     * Gets the value of the modelid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelid() {
        return modelid;
    }

    /**
     * Sets the value of the modelid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelid(String value) {
        this.modelid = value;
    }

    /**
     * Gets the value of the modeltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeltype() {
        return modeltype;
    }

    /**
     * Sets the value of the modeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeltype(String value) {
        this.modeltype = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
