//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.05 at 06:45:13 PM EST 
//


package edu.pitt.rods.research.apollo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.rods.research.apollo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.rods.research.apollo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NamedDecimalValueType }
     * 
     */
    public NamedDecimalValueType createNamedDecimalValueType() {
        return new NamedDecimalValueType();
    }

    /**
     * Create an instance of {@link NamedStringValueType }
     * 
     */
    public NamedStringValueType createNamedStringValueType() {
        return new NamedStringValueType();
    }

    /**
     * Create an instance of {@link NamedGYearArrayType }
     * 
     */
    public NamedGYearArrayType createNamedGYearArrayType() {
        return new NamedGYearArrayType();
    }

    /**
     * Create an instance of {@link NamedGYearMonthArrayType }
     * 
     */
    public NamedGYearMonthArrayType createNamedGYearMonthArrayType() {
        return new NamedGYearMonthArrayType();
    }

    /**
     * Create an instance of {@link NamedDecimalArrayType }
     * 
     */
    public NamedDecimalArrayType createNamedDecimalArrayType() {
        return new NamedDecimalArrayType();
    }

    /**
     * Create an instance of {@link NamedBase64BinaryArrayType }
     * 
     */
    public NamedBase64BinaryArrayType createNamedBase64BinaryArrayType() {
        return new NamedBase64BinaryArrayType();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType }
     * 
     */
    public AgentBasedModelRunRequestObjType createAgentBasedModelRunRequestObjType() {
        return new AgentBasedModelRunRequestObjType();
    }

    /**
     * Create an instance of {@link NamedBooleanArrayType }
     * 
     */
    public NamedBooleanArrayType createNamedBooleanArrayType() {
        return new NamedBooleanArrayType();
    }

    /**
     * Create an instance of {@link NamedTimeValueType }
     * 
     */
    public NamedTimeValueType createNamedTimeValueType() {
        return new NamedTimeValueType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunResponseObjType.Results.Recognized }
     * 
     */
    public CompartmentModelRunResponseObjType.Results.Recognized createCompartmentModelRunResponseObjTypeResultsRecognized() {
        return new CompartmentModelRunResponseObjType.Results.Recognized();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes.Susceptible }
     * 
     */
    public SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes.Susceptible createSEIRModelRunRequestObjTypeParametersRecognizedInitialCompartmentSizesSusceptible() {
        return new SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes.Susceptible();
    }

    /**
     * Create an instance of {@link CompartmentModelRunRequestObjType }
     * 
     */
    public CompartmentModelRunRequestObjType createCompartmentModelRunRequestObjType() {
        return new CompartmentModelRunRequestObjType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunRequestObjType.Parameters.Recognized.ProphylaxisSchedule }
     * 
     */
    public CompartmentModelRunRequestObjType.Parameters.Recognized.ProphylaxisSchedule createCompartmentModelRunRequestObjTypeParametersRecognizedProphylaxisSchedule() {
        return new CompartmentModelRunRequestObjType.Parameters.Recognized.ProphylaxisSchedule();
    }

    /**
     * Create an instance of {@link SEIRModelRunResponseObjType.Results.Recognized.EpiCurve }
     * 
     */
    public SEIRModelRunResponseObjType.Results.Recognized.EpiCurve createSEIRModelRunResponseObjTypeResultsRecognizedEpiCurve() {
        return new SEIRModelRunResponseObjType.Results.Recognized.EpiCurve();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType.Parameters.Recognized }
     * 
     */
    public AgentBasedModelRunRequestObjType.Parameters.Recognized createAgentBasedModelRunRequestObjTypeParametersRecognized() {
        return new AgentBasedModelRunRequestObjType.Parameters.Recognized();
    }

    /**
     * Create an instance of {@link SEIRModelRunResponseObjType.Results }
     * 
     */
    public SEIRModelRunResponseObjType.Results createSEIRModelRunResponseObjTypeResults() {
        return new SEIRModelRunResponseObjType.Results();
    }

    /**
     * Create an instance of {@link NamedTimeArrayType }
     * 
     */
    public NamedTimeArrayType createNamedTimeArrayType() {
        return new NamedTimeArrayType();
    }

    /**
     * Create an instance of {@link NamedFloatArrayType }
     * 
     */
    public NamedFloatArrayType createNamedFloatArrayType() {
        return new NamedFloatArrayType();
    }

    /**
     * Create an instance of {@link NamedGYearMonthValueType }
     * 
     */
    public NamedGYearMonthValueType createNamedGYearMonthValueType() {
        return new NamedGYearMonthValueType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunResponseObjType }
     * 
     */
    public CompartmentModelRunResponseObjType createCompartmentModelRunResponseObjType() {
        return new CompartmentModelRunResponseObjType();
    }

    /**
     * Create an instance of {@link SEIRModelRunResponseObjType }
     * 
     */
    public SEIRModelRunResponseObjType createSEIRModelRunResponseObjType() {
        return new SEIRModelRunResponseObjType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunResponseObjType.Results }
     * 
     */
    public CompartmentModelRunResponseObjType.Results createCompartmentModelRunResponseObjTypeResults() {
        return new CompartmentModelRunResponseObjType.Results();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunResponseObjType.Results.Recognized }
     * 
     */
    public AgentBasedModelRunResponseObjType.Results.Recognized createAgentBasedModelRunResponseObjTypeResultsRecognized() {
        return new AgentBasedModelRunResponseObjType.Results.Recognized();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunResponseObjType }
     * 
     */
    public AgentBasedModelRunResponseObjType createAgentBasedModelRunResponseObjType() {
        return new AgentBasedModelRunResponseObjType();
    }

    /**
     * Create an instance of {@link NamedDurationArrayType }
     * 
     */
    public NamedDurationArrayType createNamedDurationArrayType() {
        return new NamedDurationArrayType();
    }

    /**
     * Create an instance of {@link NamedGMonthDayValueType }
     * 
     */
    public NamedGMonthDayValueType createNamedGMonthDayValueType() {
        return new NamedGMonthDayValueType();
    }

    /**
     * Create an instance of {@link UnrecognizedParametersDescriptionObjType }
     * 
     */
    public UnrecognizedParametersDescriptionObjType createUnrecognizedParametersDescriptionObjType() {
        return new UnrecognizedParametersDescriptionObjType();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunResponseObjType.Results }
     * 
     */
    public AgentBasedModelRunResponseObjType.Results createAgentBasedModelRunResponseObjTypeResults() {
        return new AgentBasedModelRunResponseObjType.Results();
    }

    /**
     * Create an instance of {@link NamedGMonthValueType }
     * 
     */
    public NamedGMonthValueType createNamedGMonthValueType() {
        return new NamedGMonthValueType();
    }

    /**
     * Create an instance of {@link NamedAnyURIValueType }
     * 
     */
    public NamedAnyURIValueType createNamedAnyURIValueType() {
        return new NamedAnyURIValueType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunRequestObjType.Parameters.Recognized }
     * 
     */
    public CompartmentModelRunRequestObjType.Parameters.Recognized createCompartmentModelRunRequestObjTypeParametersRecognized() {
        return new CompartmentModelRunRequestObjType.Parameters.Recognized();
    }

    /**
     * Create an instance of {@link BaseModelParamObjType }
     * 
     */
    public BaseModelParamObjType createBaseModelParamObjType() {
        return new BaseModelParamObjType();
    }

    /**
     * Create an instance of {@link NamedDateTimeValueType }
     * 
     */
    public NamedDateTimeValueType createNamedDateTimeValueType() {
        return new NamedDateTimeValueType();
    }

    /**
     * Create an instance of {@link NamedDoubleArrayType }
     * 
     */
    public NamedDoubleArrayType createNamedDoubleArrayType() {
        return new NamedDoubleArrayType();
    }

    /**
     * Create an instance of {@link ModelID }
     * 
     */
    public ModelID createModelID() {
        return new ModelID();
    }

    /**
     * Create an instance of {@link NamedDateValueType }
     * 
     */
    public NamedDateValueType createNamedDateValueType() {
        return new NamedDateValueType();
    }

    /**
     * Create an instance of {@link NamedDoubleValueType }
     * 
     */
    public NamedDoubleValueType createNamedDoubleValueType() {
        return new NamedDoubleValueType();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunResponseObjType.Results.Recognized.EpiCurve }
     * 
     */
    public AgentBasedModelRunResponseObjType.Results.Recognized.EpiCurve createAgentBasedModelRunResponseObjTypeResultsRecognizedEpiCurve() {
        return new AgentBasedModelRunResponseObjType.Results.Recognized.EpiCurve();
    }

    /**
     * Create an instance of {@link NamedHexBinaryArrayType }
     * 
     */
    public NamedHexBinaryArrayType createNamedHexBinaryArrayType() {
        return new NamedHexBinaryArrayType();
    }

    /**
     * Create an instance of {@link NamedDateArrayType }
     * 
     */
    public NamedDateArrayType createNamedDateArrayType() {
        return new NamedDateArrayType();
    }

    /**
     * Create an instance of {@link SupportedTypeCollectionType }
     * 
     */
    public SupportedTypeCollectionType createSupportedTypeCollectionType() {
        return new SupportedTypeCollectionType();
    }

    /**
     * Create an instance of {@link NamedDurationValueType }
     * 
     */
    public NamedDurationValueType createNamedDurationValueType() {
        return new NamedDurationValueType();
    }

    /**
     * Create an instance of {@link NamedGMonthArrayType }
     * 
     */
    public NamedGMonthArrayType createNamedGMonthArrayType() {
        return new NamedGMonthArrayType();
    }

    /**
     * Create an instance of {@link NamedGDayArrayType }
     * 
     */
    public NamedGDayArrayType createNamedGDayArrayType() {
        return new NamedGDayArrayType();
    }

    /**
     * Create an instance of {@link NamedBooleanValueType }
     * 
     */
    public NamedBooleanValueType createNamedBooleanValueType() {
        return new NamedBooleanValueType();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType.Parameters.Recognized }
     * 
     */
    public SEIRModelRunRequestObjType.Parameters.Recognized createSEIRModelRunRequestObjTypeParametersRecognized() {
        return new SEIRModelRunRequestObjType.Parameters.Recognized();
    }

    /**
     * Create an instance of {@link SEIRModelRunResponseObjType.Results.Recognized }
     * 
     */
    public SEIRModelRunResponseObjType.Results.Recognized createSEIRModelRunResponseObjTypeResultsRecognized() {
        return new SEIRModelRunResponseObjType.Results.Recognized();
    }

    /**
     * Create an instance of {@link NamedHexBinaryValueType }
     * 
     */
    public NamedHexBinaryValueType createNamedHexBinaryValueType() {
        return new NamedHexBinaryValueType();
    }

    /**
     * Create an instance of {@link UnnamedDoubleArrayType }
     * 
     */
    public UnnamedDoubleArrayType createUnnamedDoubleArrayType() {
        return new UnnamedDoubleArrayType();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType.Parameters }
     * 
     */
    public AgentBasedModelRunRequestObjType.Parameters createAgentBasedModelRunRequestObjTypeParameters() {
        return new AgentBasedModelRunRequestObjType.Parameters();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType.Parameters }
     * 
     */
    public SEIRModelRunRequestObjType.Parameters createSEIRModelRunRequestObjTypeParameters() {
        return new SEIRModelRunRequestObjType.Parameters();
    }

    /**
     * Create an instance of {@link NamedStringArrayType }
     * 
     */
    public NamedStringArrayType createNamedStringArrayType() {
        return new NamedStringArrayType();
    }

    /**
     * Create an instance of {@link RunResultRequestObjType }
     * 
     */
    public RunResultRequestObjType createRunResultRequestObjType() {
        return new RunResultRequestObjType();
    }

    /**
     * Create an instance of {@link NamedAnyURIArrayType }
     * 
     */
    public NamedAnyURIArrayType createNamedAnyURIArrayType() {
        return new NamedAnyURIArrayType();
    }

    /**
     * Create an instance of {@link NamedGDayValueType }
     * 
     */
    public NamedGDayValueType createNamedGDayValueType() {
        return new NamedGDayValueType();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo.VaccineTemporalDistribution }
     * 
     */
    public AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo.VaccineTemporalDistribution createAgentBasedModelRunRequestObjTypeParametersRecognizedVaccinationScheduleControlMeasureInfoVaccineTemporalDistribution() {
        return new AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo.VaccineTemporalDistribution();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType }
     * 
     */
    public SEIRModelRunRequestObjType createSEIRModelRunRequestObjType() {
        return new SEIRModelRunRequestObjType();
    }

    /**
     * Create an instance of {@link CompartmentModelRunResponseObjType.Results.Recognized.EpiCurve }
     * 
     */
    public CompartmentModelRunResponseObjType.Results.Recognized.EpiCurve createCompartmentModelRunResponseObjTypeResultsRecognizedEpiCurve() {
        return new CompartmentModelRunResponseObjType.Results.Recognized.EpiCurve();
    }

    /**
     * Create an instance of {@link NamedBase64BinaryValueType }
     * 
     */
    public NamedBase64BinaryValueType createNamedBase64BinaryValueType() {
        return new NamedBase64BinaryValueType();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType.Parameters.Recognized.VaccinationSchedule }
     * 
     */
    public SEIRModelRunRequestObjType.Parameters.Recognized.VaccinationSchedule createSEIRModelRunRequestObjTypeParametersRecognizedVaccinationSchedule() {
        return new SEIRModelRunRequestObjType.Parameters.Recognized.VaccinationSchedule();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo }
     * 
     */
    public AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo createAgentBasedModelRunRequestObjTypeParametersRecognizedVaccinationScheduleControlMeasureInfo() {
        return new AgentBasedModelRunRequestObjType.Parameters.Recognized.VaccinationScheduleControlMeasureInfo();
    }

    /**
     * Create an instance of {@link NamedFloatValueType }
     * 
     */
    public NamedFloatValueType createNamedFloatValueType() {
        return new NamedFloatValueType();
    }

    /**
     * Create an instance of {@link NamedGMonthDayArrayType }
     * 
     */
    public NamedGMonthDayArrayType createNamedGMonthDayArrayType() {
        return new NamedGMonthDayArrayType();
    }

    /**
     * Create an instance of {@link SEIRModelRunResponseObjType.Results.Recognized.ControlMeasureAdministrationCurve }
     * 
     */
    public SEIRModelRunResponseObjType.Results.Recognized.ControlMeasureAdministrationCurve createSEIRModelRunResponseObjTypeResultsRecognizedControlMeasureAdministrationCurve() {
        return new SEIRModelRunResponseObjType.Results.Recognized.ControlMeasureAdministrationCurve();
    }

    /**
     * Create an instance of {@link CompartmentModelRunRequestObjType.Parameters }
     * 
     */
    public CompartmentModelRunRequestObjType.Parameters createCompartmentModelRunRequestObjTypeParameters() {
        return new CompartmentModelRunRequestObjType.Parameters();
    }

    /**
     * Create an instance of {@link AgentBasedModelRunRequestObjType.Parameters.Recognized.SchoolClosureControlMeasureInfo }
     * 
     */
    public AgentBasedModelRunRequestObjType.Parameters.Recognized.SchoolClosureControlMeasureInfo createAgentBasedModelRunRequestObjTypeParametersRecognizedSchoolClosureControlMeasureInfo() {
        return new AgentBasedModelRunRequestObjType.Parameters.Recognized.SchoolClosureControlMeasureInfo();
    }

    /**
     * Create an instance of {@link CompartmentModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes }
     * 
     */
    public CompartmentModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes createCompartmentModelRunRequestObjTypeParametersRecognizedInitialCompartmentSizes() {
        return new CompartmentModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes();
    }

    /**
     * Create an instance of {@link NamedDateTimeArrayType }
     * 
     */
    public NamedDateTimeArrayType createNamedDateTimeArrayType() {
        return new NamedDateTimeArrayType();
    }

    /**
     * Create an instance of {@link NamedGYearValueType }
     * 
     */
    public NamedGYearValueType createNamedGYearValueType() {
        return new NamedGYearValueType();
    }

    /**
     * Create an instance of {@link SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes }
     * 
     */
    public SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes createSEIRModelRunRequestObjTypeParametersRecognizedInitialCompartmentSizes() {
        return new SEIRModelRunRequestObjType.Parameters.Recognized.InitialCompartmentSizes();
    }

}
