//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 05:08:40 PM EST 
//


package edu.pitt.rods.research.apollo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RunStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SUBMITTED"/>
 *     &lt;enumeration value="QUEUED"/>
 *     &lt;enumeration value="RUNNING"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="FAILED"/>
 *     &lt;enumeration value="UNAUTHORIZED"/>
 *     &lt;enumeration value="UNKNOWN_ID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RunStatusEnum")
@XmlEnum
public enum RunStatusEnum {

    SUBMITTED,
    QUEUED,
    RUNNING,
    COMPLETED,
    FAILED,
    UNAUTHORIZED,
    UNKNOWN_ID;

    public String value() {
        return name();
    }

    public static RunStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
