<?php
/*

    Copyright (C) 2011 University of Pittsburgh

    This file is part of Apollo.

    Apollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.

    Apollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with Apollo.  If not, see <http://www.gnu.org/licenses/>.

*/

/**
 *
 * @author Yang Hu <yah14@pitt.edu>
 */
//namespace models;

function get_time_granularity_text() {
	return "Temporal Granularity";
}

function get_temporal_increment_text() {
	return "Temporal Increment";
}

function get_run_length_text() {
	return "Run Length";
}

function get_username_text() {
	return "Username";
}

function get_password_text() {
	return "Password";
}

function get_edit_hint_text() {
	return '<div class="ui-icon ui-icon-pencil"></div>';
}

function get_reg_icon_text() {
	return '<div class="ui-icon ui-icon-squaresmall-minus"></div>';
}

function get_unreg_icon_text() {
	return '<div class="ui-icon ui-icon-circlesmall-minus"></div>';;
}
?>