//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 05:08:40 PM EST 
//


package edu.pitt.rods.research.apollo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompartmentModelRunRequestObjType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompartmentModelRunRequestObjType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModelID" type="{http://research.rods.pitt.edu/apollo/}ModelID"/>
 *         &lt;element name="Parameters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="registered">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://research.rods.pitt.edu/apollo/}BaseModelParamObjType">
 *                           &lt;sequence>
 *                             &lt;element name="InitialCompartmentSizes">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="named_Compartment" type="{http://research.rods.pitt.edu/apollo/}named_decimal_value_type" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ProphylaxisSchedule">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="BeginTreatmentInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ProphylaxisEfficacy">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ProdromalTreatmentEfficacy">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="FulminantTreatmentEfficacy">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Unregistered" type="{http://research.rods.pitt.edu/apollo/}SupportedTypeCollectionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompartmentModelRunRequestObjType", propOrder = {
    "modelID",
    "parameters"
})
public class CompartmentModelRunRequestObjType {

    @XmlElement(name = "ModelID", required = true)
    protected ModelID modelID;
    @XmlElement(name = "Parameters", required = true)
    protected CompartmentModelRunRequestObjType.Parameters parameters;

    /**
     * Gets the value of the modelID property.
     * 
     * @return
     *     possible object is
     *     {@link ModelID }
     *     
     */
    public ModelID getModelID() {
        return modelID;
    }

    /**
     * Sets the value of the modelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelID }
     *     
     */
    public void setModelID(ModelID value) {
        this.modelID = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link CompartmentModelRunRequestObjType.Parameters }
     *     
     */
    public CompartmentModelRunRequestObjType.Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompartmentModelRunRequestObjType.Parameters }
     *     
     */
    public void setParameters(CompartmentModelRunRequestObjType.Parameters value) {
        this.parameters = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="registered">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://research.rods.pitt.edu/apollo/}BaseModelParamObjType">
     *                 &lt;sequence>
     *                   &lt;element name="InitialCompartmentSizes">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="named_Compartment" type="{http://research.rods.pitt.edu/apollo/}named_decimal_value_type" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ProphylaxisSchedule">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="BeginTreatmentInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ProphylaxisEfficacy">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ProdromalTreatmentEfficacy">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="FulminantTreatmentEfficacy">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Unregistered" type="{http://research.rods.pitt.edu/apollo/}SupportedTypeCollectionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registered",
        "unregistered"
    })
    public static class Parameters {

        @XmlElement(required = true)
        protected CompartmentModelRunRequestObjType.Parameters.Registered registered;
        @XmlElement(name = "Unregistered", required = true)
        protected SupportedTypeCollectionType unregistered;

        /**
         * Gets the value of the registered property.
         * 
         * @return
         *     possible object is
         *     {@link CompartmentModelRunRequestObjType.Parameters.Registered }
         *     
         */
        public CompartmentModelRunRequestObjType.Parameters.Registered getRegistered() {
            return registered;
        }

        /**
         * Sets the value of the registered property.
         * 
         * @param value
         *     allowed object is
         *     {@link CompartmentModelRunRequestObjType.Parameters.Registered }
         *     
         */
        public void setRegistered(CompartmentModelRunRequestObjType.Parameters.Registered value) {
            this.registered = value;
        }

        /**
         * Gets the value of the unregistered property.
         * 
         * @return
         *     possible object is
         *     {@link SupportedTypeCollectionType }
         *     
         */
        public SupportedTypeCollectionType getUnregistered() {
            return unregistered;
        }

        /**
         * Sets the value of the unregistered property.
         * 
         * @param value
         *     allowed object is
         *     {@link SupportedTypeCollectionType }
         *     
         */
        public void setUnregistered(SupportedTypeCollectionType value) {
            this.unregistered = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://research.rods.pitt.edu/apollo/}BaseModelParamObjType">
         *       &lt;sequence>
         *         &lt;element name="InitialCompartmentSizes">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="named_Compartment" type="{http://research.rods.pitt.edu/apollo/}named_decimal_value_type" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ProphylaxisSchedule">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="BeginTreatmentInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ProphylaxisEfficacy">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ProdromalTreatmentEfficacy">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="FulminantTreatmentEfficacy">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initialCompartmentSizes",
            "prophylaxisSchedule",
            "beginTreatmentInterval",
            "prophylaxisEfficacy",
            "prodromalTreatmentEfficacy",
            "fulminantTreatmentEfficacy"
        })
        public static class Registered
            extends BaseModelParamObjType
        {

            @XmlElement(name = "InitialCompartmentSizes", required = true)
            protected CompartmentModelRunRequestObjType.Parameters.Registered.InitialCompartmentSizes initialCompartmentSizes;
            @XmlElement(name = "ProphylaxisSchedule", required = true)
            protected CompartmentModelRunRequestObjType.Parameters.Registered.ProphylaxisSchedule prophylaxisSchedule;
            @XmlElement(name = "BeginTreatmentInterval")
            protected int beginTreatmentInterval;
            @XmlElement(name = "ProphylaxisEfficacy")
            protected int prophylaxisEfficacy;
            @XmlElement(name = "ProdromalTreatmentEfficacy")
            protected int prodromalTreatmentEfficacy;
            @XmlElement(name = "FulminantTreatmentEfficacy")
            protected int fulminantTreatmentEfficacy;

            /**
             * Gets the value of the initialCompartmentSizes property.
             * 
             * @return
             *     possible object is
             *     {@link CompartmentModelRunRequestObjType.Parameters.Registered.InitialCompartmentSizes }
             *     
             */
            public CompartmentModelRunRequestObjType.Parameters.Registered.InitialCompartmentSizes getInitialCompartmentSizes() {
                return initialCompartmentSizes;
            }

            /**
             * Sets the value of the initialCompartmentSizes property.
             * 
             * @param value
             *     allowed object is
             *     {@link CompartmentModelRunRequestObjType.Parameters.Registered.InitialCompartmentSizes }
             *     
             */
            public void setInitialCompartmentSizes(CompartmentModelRunRequestObjType.Parameters.Registered.InitialCompartmentSizes value) {
                this.initialCompartmentSizes = value;
            }

            /**
             * Gets the value of the prophylaxisSchedule property.
             * 
             * @return
             *     possible object is
             *     {@link CompartmentModelRunRequestObjType.Parameters.Registered.ProphylaxisSchedule }
             *     
             */
            public CompartmentModelRunRequestObjType.Parameters.Registered.ProphylaxisSchedule getProphylaxisSchedule() {
                return prophylaxisSchedule;
            }

            /**
             * Sets the value of the prophylaxisSchedule property.
             * 
             * @param value
             *     allowed object is
             *     {@link CompartmentModelRunRequestObjType.Parameters.Registered.ProphylaxisSchedule }
             *     
             */
            public void setProphylaxisSchedule(CompartmentModelRunRequestObjType.Parameters.Registered.ProphylaxisSchedule value) {
                this.prophylaxisSchedule = value;
            }

            /**
             * Gets the value of the beginTreatmentInterval property.
             * 
             */
            public int getBeginTreatmentInterval() {
                return beginTreatmentInterval;
            }

            /**
             * Sets the value of the beginTreatmentInterval property.
             * 
             */
            public void setBeginTreatmentInterval(int value) {
                this.beginTreatmentInterval = value;
            }

            /**
             * Gets the value of the prophylaxisEfficacy property.
             * 
             */
            public int getProphylaxisEfficacy() {
                return prophylaxisEfficacy;
            }

            /**
             * Sets the value of the prophylaxisEfficacy property.
             * 
             */
            public void setProphylaxisEfficacy(int value) {
                this.prophylaxisEfficacy = value;
            }

            /**
             * Gets the value of the prodromalTreatmentEfficacy property.
             * 
             */
            public int getProdromalTreatmentEfficacy() {
                return prodromalTreatmentEfficacy;
            }

            /**
             * Sets the value of the prodromalTreatmentEfficacy property.
             * 
             */
            public void setProdromalTreatmentEfficacy(int value) {
                this.prodromalTreatmentEfficacy = value;
            }

            /**
             * Gets the value of the fulminantTreatmentEfficacy property.
             * 
             */
            public int getFulminantTreatmentEfficacy() {
                return fulminantTreatmentEfficacy;
            }

            /**
             * Sets the value of the fulminantTreatmentEfficacy property.
             * 
             */
            public void setFulminantTreatmentEfficacy(int value) {
                this.fulminantTreatmentEfficacy = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="named_Compartment" type="{http://research.rods.pitt.edu/apollo/}named_decimal_value_type" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "namedCompartment"
            })
            public static class InitialCompartmentSizes {

                @XmlElement(name = "named_Compartment", required = true)
                protected List<NamedDecimalValueType> namedCompartment;

                /**
                 * Gets the value of the namedCompartment property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the namedCompartment property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getNamedCompartment().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NamedDecimalValueType }
                 * 
                 * 
                 */
                public List<NamedDecimalValueType> getNamedCompartment() {
                    if (namedCompartment == null) {
                        namedCompartment = new ArrayList<NamedDecimalValueType>();
                    }
                    return this.namedCompartment;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ProphylaxisSchedule {

                @XmlElement(type = Double.class)
                protected List<Double> value;

                /**
                 * Gets the value of the value property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the value property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValue().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Double }
                 * 
                 * 
                 */
                public List<Double> getValue() {
                    if (value == null) {
                        value = new ArrayList<Double>();
                    }
                    return this.value;
                }

            }

        }

    }

}
