################################################## 
# TranslatorService_v2_0_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from TranslatorService_v2_0_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class TranslatorService_v2_0Locator:
    TranslatorServiceEI_address = "http://research.rods.pitt.edu/translatorservice2.0/services/translatorservice"
    def getTranslatorServiceEIAddress(self):
        return TranslatorService_v2_0Locator.TranslatorServiceEI_address
    def getTranslatorServiceEI(self, url=None, **kw):
        return TranslatorService_v2_0SoapBindingSOAP(url or TranslatorService_v2_0Locator.TranslatorServiceEI_address, **kw)

# Methods
class TranslatorService_v2_0SoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: translateRunSimulationMessage
    def translateRunSimulationMessage(self, request):
        if isinstance(request, translateRunSimulationMessage) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://service.apollo.pitt.edu/translatorservice/v2_0/translateRunSimulationMessage", **kw)
        # no output wsaction
        response = self.binding.Receive(translateRunSimulationMessageResponse.typecode)
        return response

translateRunSimulationMessage = ns1.translateRunSimulationMessage_Dec().pyclass

translateRunSimulationMessageResponse = ns1.translateRunSimulationMessageResponse_Dec().pyclass
