##################################################
# TranslatorService_v2_0_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.DelAuthServiceModuleWriter
#
##################################################

from TranslatorService_v2_0_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class TranslatorService_v2_0(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions name=\"TranslatorService_v2.0\" targetNamespace=\"http://service.apollo.pitt.edu/translatorservice/v2_0/\" xmlns:ns1=\"http://schemas.xmlsoap.org/soap/http\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:tns=\"http://service.apollo.pitt.edu/translatorservice/v2_0/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">
  <wsdl:types>
<xs:schema elementFormDefault=\"qualified\" targetNamespace=\"http://types.apollo.pitt.edu/v2_0/\" version=\"1.0\" xmlns:tns=\"http://types.apollo.pitt.edu/v2_0/\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
<xs:complexType name=\"RunSimulationMessage\">
    <xs:sequence>
      <xs:element name=\"simulatorIdentification\" type=\"tns:SoftwareIdentification\"/>
      <xs:element name=\"authentication\" type=\"tns:Authentication\"/>
      <xs:element name=\"simulatorTimeSpecification\" type=\"tns:SimulatorTimeSpecification\"/>
      <xs:element name=\"infectiousDiseaseScenario\" type=\"tns:InfectiousDiseaseScenario\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SoftwareIdentification\">
    <xs:sequence>
      <xs:element name=\"softwareDeveloper\" type=\"xs:token\"/>
      <xs:element name=\"softwareName\" type=\"xs:token\"/>
      <xs:element name=\"softwareVersion\" type=\"xs:token\"/>
      <xs:element name=\"softwareType\" type=\"tns:ApolloSoftwareType\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Authentication\">
    <xs:sequence>
      <xs:element name=\"requesterId\" type=\"xs:token\"/>
      <xs:element name=\"requesterPassword\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SimulatorTimeSpecification\">
    <xs:sequence>
      <xs:element name=\"timeStepUnit\" type=\"tns:TimeStepUnit\"/>
      <xs:element name=\"timeStepValue\" type=\"xs:double\"/>
      <xs:element name=\"runLength\" type=\"xs:positiveInteger\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"InfectiousDiseaseScenario\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"scenarioDate\" type=\"xs:dateTime\"/>
          <xs:element name=\"location\" type=\"tns:Location\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"infections\" type=\"tns:Infection\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"diseases\" type=\"tns:InfectiousDisease\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"contaminations\" nillable=\"true\" type=\"tns:Contamination\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"treatments\" nillable=\"true\" type=\"tns:Treatment\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"infectiousDiseaseControlStrategies\" nillable=\"true\" type=\"tns:InfectiousDiseaseControlStrategy\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"populationInfectionAndImmunityCensuses\" type=\"tns:PopulationInfectionAndImmunityCensus\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"populationTreatmentCensuses\" nillable=\"true\" type=\"tns:PopulationTreatmentCensus\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"contaminatedThingCensuses\" nillable=\"true\" type=\"tns:ContaminatedThingCensus\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ApolloIndexableItem\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"Location\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"locationCode\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"locationDefinition\" type=\"tns:LocationDefinition\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"LocationDefinition\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"locationsIncluded\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"locationsExcluded\" nillable=\"true\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Infection\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"pathogenTaxonID\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"hostTaxonID\" type=\"xs:string\"/>
          <xs:element name=\"infectiousPeriodDuration\" type=\"tns:NumericParameterValue\"/>
          <xs:element minOccurs=\"0\" name=\"infectiousness\" type=\"tns:NumericParameterValue\"/>
          <xs:element name=\"latentPeriodDuration\" type=\"tns:NumericParameterValue\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"infectionAcquisition\" type=\"tns:InfectionAcquisition\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ApolloPathogenCode\">
    <xs:sequence>
      <xs:element name=\"ncbiTaxonId\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"gisrnCladeName\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"NumericParameterValue\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"unitOfMeasure\" type=\"tns:UnitOfMeasure\"/>
      <xs:element minOccurs=\"0\" name=\"value\" type=\"xs:double\"/>
      <xs:element minOccurs=\"0\" name=\"unconditionalProbabilityDistribution\" type=\"tns:UnconditionalProbabilityDistribution\"/>
      <xs:element minOccurs=\"0\" name=\"conditionalProbabilityDistribution\" type=\"tns:ConditionalProbabilityDistribution\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"UnconditionalProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ProbabilityDistribution\">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ProbabilityDistribution\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"BayesianNetworkDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ProbabilityDistribution\">
        <xs:sequence>
          <xs:element name=\"networkStructure\" type=\"tns:BayesianNetworkStructureType\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"CPTs\" type=\"tns:ConditionalProbabilityTable\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"PPFs\" type=\"tns:PrototypicalProbabilityFunction\"/>
          <xs:element minOccurs=\"0\" name=\"GeNIE_XML\" type=\"tns:GeNIE_XMLType\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"BayesianNetworkStructureType\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"ConditionalProbabilityTable\">
    <xs:sequence>
      <xs:element name=\"axisDefinitions\" type=\"tns:ArrayDimensionsDefinition\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"pointProbabilities\" type=\"xs:double\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"parametricDistribution\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ArrayDimensionsDefinition\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"TemporalArrayDimensionsDefinition\">
    <xs:complexContent>
      <xs:extension base=\"tns:ArrayDimensionsDefinition\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"time\" type=\"xs:nonNegativeInteger\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationStrataDefinition\">
    <xs:complexContent>
      <xs:extension base=\"tns:ArrayDimensionsDefinition\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"ageRanges\" nillable=\"true\" type=\"tns:AgeRange\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"genders\" nillable=\"true\" type=\"tns:Gender\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"diseaseOutcomes\" nillable=\"true\" type=\"tns:DiseaseOutcome\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"AgeRange\">
    <xs:complexContent>
      <xs:extension base=\"tns:CategoryDefinition\">
        <xs:sequence>
          <xs:element name=\"lowerBound\" type=\"xs:nonNegativeInteger\"/>
          <xs:element name=\"upperBound\" type=\"xs:nonNegativeInteger\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"CategoryDefinition\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"FacilityCategory\">
    <xs:complexContent>
      <xs:extension base=\"tns:CategoryDefinition\">
        <xs:sequence>
          <xs:element name=\"facility\" type=\"tns:FacilityEnum\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"GenderCategory\">
    <xs:complexContent>
      <xs:extension base=\"tns:CategoryDefinition\">
        <xs:sequence>
          <xs:element name=\"gender\" type=\"tns:Gender\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PrototypicalProbabilityFunction\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"GeNIE_XMLType\">
    <xs:sequence>
      <xs:element name=\"theXML\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"DiscreteNonparametricProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:UnconditionalProbabilityDistribution\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"probabilityValuePairs\" type=\"tns:ProbabilityValuePair\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ProbabilityValuePair\">
    <xs:sequence>
      <xs:element name=\"value\" type=\"xs:double\"/>
      <xs:element name=\"probability\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"NonparametricDiscreteProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:UnconditionalProbabilityDistribution\">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ParametricProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:UnconditionalProbabilityDistribution\">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"DiscreteParametricProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ParametricProbabilityDistribution\">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ContinuousParametricProbabilityDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ParametricProbabilityDistribution\">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"GammaDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ContinuousParametricProbabilityDistribution\">
        <xs:sequence>
          <xs:element name=\"k-shape\" type=\"xs:double\"/>
          <xs:element name=\"theta-scale\" type=\"xs:double\"/>
          <xs:element name=\"shiftRight\" type=\"xs:double\"/>
          <xs:element name=\"cutTailAt\" type=\"xs:double\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"WeibullDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ContinuousParametricProbabilityDistribution\">
        <xs:sequence>
          <xs:element name=\"k-shape\" type=\"xs:double\"/>
          <xs:element name=\"lambda-scale\" type=\"xs:double\"/>
          <xs:element name=\"shiftRight\" type=\"xs:double\"/>
          <xs:element name=\"cutTailAt\" type=\"xs:double\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"LogNormalDistribution\">
    <xs:complexContent>
      <xs:extension base=\"tns:ContinuousParametricProbabilityDistribution\">
        <xs:sequence>
          <xs:element name=\"mean\" type=\"xs:double\"/>
          <xs:element name=\"standardDeviation\" type=\"xs:double\"/>
          <xs:element name=\"shiftRight\" type=\"xs:double\"/>
          <xs:element name=\"cutTailAt\" type=\"xs:double\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ConditionalProbabilityDistribution\">
    <xs:sequence>
      <xs:element name=\"firstConditioningVariable\" type=\"tns:ConditioningVariable\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ConditioningVariable\">
    <xs:sequence>
      <xs:element name=\"variableName\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"values\" type=\"tns:Category\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Category\">
    <xs:sequence>
      <xs:element name=\"categoryDefinition\" type=\"tns:CategoryDefinition\"/>
      <xs:element minOccurs=\"0\" name=\"unconditionalProbabilityDistribution\" type=\"tns:UnconditionalProbabilityDistribution\"/>
      <xs:element minOccurs=\"0\" name=\"conditioningVariable\" type=\"tns:ConditioningVariable\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"InfectionAcquisition\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"pathogenTaxonID\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"susceptibleHostTaxonID\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"infectiousHostTaxonID\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"contaminatedMaterialID\" type=\"xs:token\"/>
          <xs:element minOccurs=\"0\" name=\"basicReproductionNumber\" type=\"xs:double\"/>
          <xs:element minOccurs=\"0\" name=\"imperialReproductionNumber\" type=\"tns:ImperialReproductionNumber\"/>
          <xs:element minOccurs=\"0\" name=\"transmissionProbability\" type=\"tns:ProbabilisticParameterValue\"/>
          <xs:element minOccurs=\"0\" name=\"transmissionCoefficient\" type=\"tns:NumericParameterValue\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ImperialReproductionNumber\">
    <xs:sequence>
      <xs:element name=\"averageCommunityImperialReproductionNumber\" type=\"xs:double\"/>
      <xs:element name=\"averageHouseholdImperialReproductionNumber\" type=\"xs:double\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"imperialReproductionNumberForPlace\" nillable=\"true\" type=\"tns:ImperialReproductionNumberForPlace\"/>
      <xs:element name=\"seasonalityFunctionParameters\" type=\"tns:SeasonalityFunctionParameters\"/>
      <xs:element name=\"probSymptomaticInfectionClinicallyDetected\" type=\"xs:double\"/>
      <xs:element name=\"symptomaticInfectionMultiplier\" type=\"xs:double\"/>
      <xs:element name=\"probSevereInfectionClinicallyDetected\" type=\"xs:double\"/>
      <xs:element name=\"severeInfectionMultiplier\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ImperialReproductionNumberForPlace\">
    <xs:sequence>
      <xs:element name=\"placeType\" type=\"tns:FacilityEnum\"/>
      <xs:element name=\"averageImperialReproductionNumber\" type=\"xs:double\"/>
      <xs:element name=\"withinGroupTransmissionProbability\" type=\"xs:double\"/>
      <xs:element name=\"probSymptomaticIndividualAbsent\" type=\"xs:double\"/>
      <xs:element name=\"symptomaticAbsenteeMultiplier\" type=\"xs:double\"/>
      <xs:element name=\"probSeverelyInfectedIndividualAbsent\" type=\"xs:double\"/>
      <xs:element name=\"severelyInfectedAbsenteeMultiplier\" type=\"xs:double\"/>
      <xs:element name=\"spatialKernelFunctionParameters\" type=\"tns:SpatialKernelFunctionParameters\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SpatialKernelFunctionParameters\">
    <xs:sequence>
      <xs:element name=\"type\" type=\"xs:token\"/>
      <xs:element name=\"a0\" type=\"xs:double\"/>
      <xs:element name=\"a1\" type=\"xs:double\"/>
      <xs:element name=\"b0\" type=\"xs:double\"/>
      <xs:element name=\"b1\" type=\"xs:double\"/>
      <xs:element name=\"c1\" type=\"xs:double\"/>
      <xs:element name=\"cutoff\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SeasonalityFunctionParameters\">
    <xs:sequence>
      <xs:element name=\"maximumSeasonalLatitude\" type=\"xs:double\"/>
      <xs:element name=\"minimumSeasonalLatitude\" type=\"xs:double\"/>
      <xs:element name=\"seasonalTemporalOffset\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ProbabilisticParameterValue\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"value\" type=\"xs:double\"/>
      <xs:element minOccurs=\"0\" name=\"unconditionalProbabilityDistribution\" type=\"tns:UnconditionalProbabilityDistribution\"/>
      <xs:element minOccurs=\"0\" name=\"conditionalProbabilityDistribution\" type=\"tns:ConditionalProbabilityDistribution\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"DecisionAnalysis\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"decisionModel\" type=\"tns:DecisionModel\"/>
          <xs:element name=\"baseCaseResult \" type=\"tns:BaseCaseResult\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"sensitivityAnalyses\" nillable=\"true\" type=\"tns:SensitivityAnalysis\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"DecisionModel\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"decisionAlternatives\" type=\"tns:DecisionAlternative\"/>
          <xs:element minOccurs=\"0\" name=\"simulatorConfiguration \" type=\"tns:RunSimulationMessage\"/>
          <xs:element name=\"utilityFunction\" type=\"tns:UtilityFunction\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"DecisionAlternative\">
    <xs:sequence>
      <xs:element name=\"singleStrategy\" type=\"xs:string\"/>
      <xs:element name=\"combinationStrategy\" type=\"xs:string\"/>
      <xs:element name=\"SequentialCombinationStrategy\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"UtilityFunction\">
    <xs:sequence>
      <xs:element name=\"lambdaFunction\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"textDescription\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"BaseCaseResult\">
    <xs:sequence>
      <xs:element maxOccurs=\"unbounded\" name=\"decisionAlternatives\" type=\"tns:DecisionAlternative\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"expectedUtilities\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SensitivityAnalysis\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"InfectiousDisease\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"diseaseID\" type=\"xs:token\"/>
          <xs:element name=\"speciesWithDisease\" type=\"xs:string\"/>
          <xs:element name=\"causalPathogen\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"diseaseOutcomes\" nillable=\"true\" type=\"tns:DiseaseOutcomeAndProbability\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"DiseaseOutcomeAndProbability\">
    <xs:sequence>
      <xs:element name=\"diseaseOutcome\" type=\"tns:DiseaseOutcome\"/>
      <xs:element name=\"probability\" type=\"tns:ProbabilisticParameterValue\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"CensusData\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element minOccurs=\"0\" name=\"date\" type=\"xs:dateTime\"/>
          <xs:element name=\"location\" type=\"tns:Location\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ContaminatedThingCensusData\">
    <xs:complexContent>
      <xs:extension base=\"tns:CensusData\">
        <xs:sequence>
          <xs:element name=\"fractionContaminated\" type=\"xs:double\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"exceptionSublocations\" nillable=\"true\" type=\"tns:ContaminatedThingCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationInfectionAndImmunityCensusData\">
    <xs:complexContent>
      <xs:extension base=\"tns:CensusData\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"censusDataCells\" type=\"tns:PopulationInfectionAndImmunityCensusDataCell\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"exceptionSubpopulations\" nillable=\"true\" type=\"tns:PopulationInfectionAndImmunityCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationInfectionAndImmunityCensusDataCell\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"ageRange\" type=\"tns:AgeRange\"/>
      <xs:element minOccurs=\"0\" name=\"gender\" type=\"tns:Gender\"/>
      <xs:element name=\"infectionState\" type=\"tns:InfectionState\"/>
      <xs:element name=\"fractionInInfectionState\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"PopulationTreatmentCensusData\">
    <xs:complexContent>
      <xs:extension base=\"tns:CensusData\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"treatmentCensusDataCells\" type=\"tns:PopulationTreatmentCensusDataCell\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"exceptionSubpopulations\" nillable=\"true\" type=\"tns:PopulationTreatmentCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationTreatmentCensusDataCell\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"ageRange\" type=\"tns:AgeRange\"/>
      <xs:element minOccurs=\"0\" name=\"gender\" type=\"tns:Gender\"/>
      <xs:element name=\"treatmentState\" type=\"tns:TreatmentState\"/>
      <xs:element name=\"fractionInInfectionState\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Contamination\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"pathogenTaxonID\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"abioticEcosystemElement\" type=\"tns:AbioticEcosystemEnum\"/>
          <xs:element name=\"contaminatedPeriod\" type=\"tns:NumericParameterValue\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"contaminationAcquisition\" type=\"tns:ContaminationAcquisition\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ContaminationAcquisition\">
    <xs:sequence>
      <xs:element name=\"abioticEcosystemElement\" type=\"tns:AbioticEcosystemEnum\"/>
      <xs:element name=\"pathogenTaxonID\" type=\"tns:ApolloPathogenCode\"/>
      <xs:element minOccurs=\"0\" name=\"infectiousHostSource\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"contaminatedSource\" type=\"xs:token\"/>
      <xs:element name=\"contaminationProbability\" type=\"tns:ProbabilisticParameterValue\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Census\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"description\" type=\"xs:string\"/>
          <xs:element name=\"location\" type=\"tns:Location\"/>
          <xs:element name=\"date\" type=\"xs:dateTime\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationAndEnvironmentCensus\">
    <xs:complexContent>
      <xs:extension base=\"tns:Census\">
        <xs:sequence>
          <xs:element minOccurs=\"0\" name=\"nameOfAdministativeUnit\" type=\"xs:token\"/>
          <xs:element name=\"numberOfPeople\" type=\"xs:integer\"/>
          <xs:element name=\"numberOfSchools\" type=\"xs:integer\"/>
          <xs:element name=\"numberOfWorkplaces\" type=\"xs:integer\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"subLocationCensuses\" nillable=\"true\" type=\"tns:PopulationAndEnvironmentCensus\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationInfectionAndImmunityCensus\">
    <xs:complexContent>
      <xs:extension base=\"tns:Census\">
        <xs:sequence>
          <xs:element name=\"populationSpecies\" type=\"xs:string\"/>
          <xs:element name=\"pathogen\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"censusData\" type=\"tns:PopulationInfectionAndImmunityCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"PopulationTreatmentCensus\">
    <xs:complexContent>
      <xs:extension base=\"tns:Census\">
        <xs:sequence>
          <xs:element name=\"populationSpecies\" type=\"xs:string\"/>
          <xs:element name=\"treatment\" type=\"tns:Treatment\"/>
          <xs:element name=\"treatmentCensusData\" type=\"tns:PopulationTreatmentCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"Treatment\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"description\" type=\"xs:string\"/>
          <xs:element name=\"speciesOfTreatedOrganisms\" type=\"xs:string\"/>
          <xs:element name=\"numDosesInTreatmentCourse\" type=\"xs:positiveInteger\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"treatmentContraindications\" nillable=\"true\" type=\"tns:TreatmentContraindication\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"TreatmentContraindication\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"description\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"simulatorReferencablePopulation\" type=\"tns:PopulationStrataDefinition\"/>
      <xs:element minOccurs=\"0\" name=\"fractionOfSimulatorReferencablePopulation\" type=\"xs:double\"/>
      <xs:element minOccurs=\"0\" name=\"pregnancy\" type=\"xs:boolean\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AntiviralTreatment\">
    <xs:complexContent>
      <xs:extension base=\"tns:Treatment\">
        <xs:sequence>
          <xs:element name=\"antiviral\" type=\"tns:Antiviral\"/>
          <xs:element name=\"antiviralTreatmentEfficacy\" type=\"tns:AntiviralTreatmentEfficacy\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"Antiviral\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"antiviralId\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AntiviralTreatmentEfficacy\">
    <xs:complexContent>
      <xs:extension base=\"tns:TreatmentEfficacy\">
        <xs:sequence>
          <xs:element name=\"antiviralTreatmentIdentifier\" type=\"xs:token\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"TreatmentEfficacy\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"treatment\" type=\"tns:Treatment\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacy\">
    <xs:complexContent>
      <xs:extension base=\"tns:TreatmentEfficacy\">
        <xs:sequence>
          <xs:element name=\"vaccineIdentifier\" type=\"xs:token\"/>
          <xs:element name=\"strainIdentifier\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"hostIdentifier\" type=\"xs:string\"/>
          <xs:element name=\"forVaccinationPreventableOutcome\" type=\"tns:VaccinationPreventableOutcome\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyForSimulatorConfiguration\">
    <xs:complexContent>
      <xs:extension base=\"tns:VaccinationEfficacy\">
        <xs:sequence>
          <xs:element name=\"averageVaccinationEfficacy\" type=\"xs:double\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"vaccinationEfficacybyAgeRange\" nillable=\"true\" type=\"tns:ProbabilisticParameterValue\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"vaccinationEfficaciesByTimeSinceMostRecentDose\" nillable=\"true\" type=\"tns:VaccinationEfficacyByTimeSinceDose\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyByTimeSinceDose\">
    <xs:sequence>
      <xs:element name=\"numberOfDosesAdministered\" type=\"xs:positiveInteger\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"timeIntervalLabelDefinitions\" type=\"tns:TimeAxisCategoryLabels\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"vaccinationEfficacyByTimeSinceMostRecentDose\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"TimeAxisCategoryLabels\">
    <xs:sequence>
      <xs:element name=\"label\" type=\"xs:token\"/>
      <xs:element name=\"simulatorTimeEarliest\" type=\"xs:nonNegativeInteger\"/>
      <xs:element name=\"simulatorTimeLatest\" type=\"xs:nonNegativeInteger\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyMeasured\">
    <xs:complexContent>
      <xs:extension base=\"tns:VaccinationEfficacy\">
        <xs:sequence>
          <xs:element name=\"measuredEfficacyValue\" type=\"tns:ConditionalProbabilityTable\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyInferred\">
    <xs:complexContent>
      <xs:extension base=\"tns:VaccinationEfficacy\">
        <xs:sequence>
          <xs:element maxOccurs=\"unbounded\" name=\"inferredFromTheseStudies\" type=\"tns:VaccinationEfficacyStudy\"/>
          <xs:element minOccurs=\"0\" name=\"vaccinationEfficacyModel\" type=\"tns:BayesianNetworkDistribution\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyStudy\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"vaccinationPreventableOutcome\" type=\"tns:VaccinationPreventableOutcome\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"vaccinationEfficacyMeasured\" type=\"tns:VaccinationEfficacyMeasured\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"dataSets\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"references\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AntiviralEfficacyForSimulatorConfiguration\">
    <xs:complexContent>
      <xs:extension base=\"tns:AntiviralTreatmentEfficacy\">
        <xs:sequence>
          <xs:element name=\"averageAntiviralTreatmentEfficacy\" type=\"xs:double\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"Vaccination\">
    <xs:complexContent>
      <xs:extension base=\"tns:Treatment\">
        <xs:sequence>
          <xs:element name=\"vaccine\" type=\"tns:Vaccine\"/>
          <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"vaccinationEfficacies\" nillable=\"true\" type=\"tns:VaccinationEfficacy\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"Vaccine\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"vaccineIdentifier\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"valence\" type=\"xs:positiveInteger\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ContaminatedThingCensus\">
    <xs:complexContent>
      <xs:extension base=\"tns:Census\">
        <xs:sequence>
          <xs:element name=\"kindOfThing\" type=\"tns:AbioticEcosystemEnum\"/>
          <xs:element name=\"pathogen\" type=\"tns:ApolloPathogenCode\"/>
          <xs:element name=\"censusData\" type=\"tns:ContaminatedThingCensusData\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"InfectiousDiseaseControlStrategy\">
    <xs:complexContent>
      <xs:extension base=\"tns:ApolloIndexableItem\">
        <xs:sequence>
          <xs:element name=\"description\" type=\"xs:string\"/>
          <xs:element name=\"controlStrategyStartTime\" type=\"tns:ControlStrategyStartTime\"/>
          <xs:element name=\"controlStrategyResponseDelay\" type=\"tns:NumericParameterValue\"/>
          <xs:element name=\"controlStrategyCompliance\" type=\"tns:ProbabilisticParameterValue\"/>
          <xs:element minOccurs=\"0\" name=\"controlStrategyReactiveEndPointFraction\" type=\"xs:double\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ControlStrategyStartTime\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"FixedStartTime\">
    <xs:complexContent>
      <xs:extension base=\"tns:ControlStrategyStartTime\">
        <xs:sequence>
          <xs:element name=\"startTimeRelativeToScenarioDate\" type=\"xs:nonNegativeInteger\"/>
          <xs:element minOccurs=\"0\" name=\"stopTimeRelativeToScenarioDate\" type=\"xs:nonNegativeInteger\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ReactiveStartTime\">
    <xs:complexContent>
      <xs:extension base=\"tns:ControlStrategyStartTime\">
        <xs:sequence>
          <xs:element name=\"trigger\" type=\"tns:ReactiveTriggersDefinition\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ReactiveTriggersDefinition\">
    <xs:sequence>
      <xs:element name=\"reactiveControlStrategyTest\" type=\"xs:token\"/>
      <xs:element name=\"reactiveControlStrategyThreshold\" type=\"xs:double\"/>
      <xs:element name=\"ascertainmentFraction\" type=\"xs:double\"/>
      <xs:element name=\"ascertainmentDelay\" type=\"xs:nonNegativeInteger\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SchoolClosureControlStrategy\">
    <xs:complexContent>
      <xs:extension base=\"tns:InfectiousDiseaseControlStrategy\">
        <xs:sequence>
          <xs:element name=\"schoolClosureDuration\" type=\"xs:nonNegativeInteger\"/>
          <xs:element name=\"schoolClosureTargetFacilities\" type=\"tns:SchoolClosureTargetFacilities\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"IndividualTreatmentControlStrategy\">
    <xs:complexContent>
      <xs:extension base=\"tns:InfectiousDiseaseControlStrategy\">
        <xs:sequence>
          <xs:element name=\"individualTreatment\" type=\"tns:Treatment\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"supplySchedule\" type=\"xs:nonNegativeInteger\"/>
          <xs:element maxOccurs=\"unbounded\" name=\"administrationCapacity\" type=\"xs:nonNegativeInteger\"/>
          <xs:element name=\"targetPopulationsAndPrioritizations\" type=\"tns:ControlStrategyTargetPopulationsAndPrioritization\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ControlStrategyTargetPopulationsAndPrioritization\">
    <xs:sequence>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"controlStrategyTargetPopulationsAndPrioritization\" nillable=\"true\" type=\"tns:TargetPriorityPopulation\"/>
      <xs:element minOccurs=\"0\" name=\"controlStrategyNamedPrioritizationScheme\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"TargetPriorityPopulation\">
    <xs:sequence>
      <xs:element name=\"label\" type=\"xs:token\"/>
      <xs:element name=\"fractionOfTargetPopulationToPrioritize\" type=\"xs:double\"/>
      <xs:element name=\"priority\" type=\"xs:nonNegativeInteger\"/>
      <xs:element minOccurs=\"0\" name=\"targetPopulationDefinition\" type=\"tns:PopulationStrataDefinition\"/>
      <xs:element minOccurs=\"0\" name=\"targetPopulationDefinitionEnum\" type=\"tns:TargetPopulationDefinitionEnum\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RingIndividualTreatmentControlStrategy\">
    <xs:complexContent>
      <xs:extension base=\"tns:IndividualTreatmentControlStrategy\">
        <xs:sequence>
          <xs:element name=\"ringDiameterInMeters\" type=\"xs:nonNegativeInteger\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"MethodCallStatus\">
    <xs:sequence>
      <xs:element name=\"status\" type=\"tns:MethodCallStatusEnum\"/>
      <xs:element name=\"message\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RunSyntheticPopulationGenerationMessage\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"VisualizerResult\">
    <xs:sequence>
      <xs:element name=\"runId\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"visualizerOutputResource\" type=\"tns:UrlOutputResource\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"UrlOutputResource\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"URL\" type=\"xs:anySimpleType\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AddLibraryItemResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element minOccurs=\"0\" name=\"uuid\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"GetLibraryItemResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element name=\"curatedLibraryItemContainer\" type=\"tns:CuratedLibraryItemContainer\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"CuratedLibraryItemContainer\">
    <xs:sequence>
      <xs:element name=\"curatedLibraryItem\" type=\"tns:CatalogEntryForApolloLibraryItem\"/>
      <xs:element name=\"apolloIndexableItem\" type=\"tns:ApolloIndexableItem\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"CatalogEntryForApolloLibraryItem\">
    <xs:sequence>
      <xs:element name=\"itemDescription\" type=\"xs:string\"/>
      <xs:element name=\"itemSource\" type=\"xs:string\"/>
      <xs:element name=\"itemType\" type=\"xs:token\"/>
      <xs:element name=\"itemUuid\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"itemIndexingLabels\" nillable=\"true\" type=\"xs:token\"/>
      <xs:element name=\"itemCreationTime\" type=\"xs:dateTime\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"GetScenarioLocationCodesSupportedBySimulatorResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"locationCodes\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RunSimulationsMessage\">
    <xs:sequence>
      <xs:element name=\"batchConfigurationFile\" type=\"xs:anyURI\"/>
      <xs:element name=\"acceptCachedResults\" type=\"xs:boolean\"/>
      <xs:element name=\"softwareIdentification\" type=\"tns:SoftwareIdentification\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RunSimulationsResult\">
    <xs:sequence>
      <xs:element name=\"completedFile\" type=\"xs:anyURI\"/>
      <xs:element name=\"runId\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"GetLibraryItemUuidsResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Uuids\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"GetConfigurationFileForSimulationResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element minOccurs=\"0\" name=\"configurationFile\" type=\"xs:string\"/>
      <xs:element minOccurs=\"0\" name=\"configurationFileInHtmlFormat\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SyntheticPopulationGenerationResult\">
    <xs:sequence>
      <xs:element name=\"runId\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"syntheticPopulationOutputResource\" type=\"tns:UrlOutputResource\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RunAndSoftwareIdentification\">
    <xs:sequence>
      <xs:element name=\"runId\" type=\"xs:string\"/>
      <xs:element name=\"softwareId\" type=\"tns:SoftwareIdentification\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ServiceRegistrationRecord\">
    <xs:complexContent>
      <xs:extension base=\"tns:ServiceRecord\">
        <xs:sequence>
          <xs:element name=\"authentication\" type=\"tns:Authentication\"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType name=\"ServiceRecord\">
    <xs:sequence>
      <xs:element name=\"url\" type=\"xs:anyURI\"/>
      <xs:element name=\"softwareIdentification\" type=\"tns:SoftwareIdentification\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RunVisualizationMessage\">
    <xs:sequence>
      <xs:element name=\"visualizerIdentification\" type=\"tns:SoftwareIdentification\"/>
      <xs:element name=\"authentication\" type=\"tns:Authentication\"/>
      <xs:element name=\"visualizationOptions\" type=\"tns:VisualizationOptions\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"VisualizationOptions\">
    <xs:sequence>
      <xs:element name=\"runId\" type=\"xs:token\"/>
      <xs:element name=\"location\" type=\"xs:token\"/>
      <xs:element name=\"outputFormat\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"GetPopulationAndEnvironmentCensusResult\">
    <xs:sequence>
      <xs:element name=\"methodCallStatus\" type=\"tns:MethodCallStatus\"/>
      <xs:element name=\"populationAndEnvironmentCensus\" type=\"tns:PopulationAndEnvironmentCensus\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"RequesterIdentification\">
    <xs:sequence>
      <xs:element name=\"requesterName\" type=\"xs:token\"/>
      <xs:element name=\"requesterCompany\" type=\"xs:token\"/>
      <xs:element name=\"requesterEmail\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"Ecosystem\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"bioticEcosystem\" type=\"tns:BioticEcosystem\"/>
      <xs:element name=\"abioticEcosystem\" type=\"tns:AbioticEcosystem\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"BioticEcosystem\">
    <xs:sequence>
      <xs:element maxOccurs=\"unbounded\" name=\"communities\" type=\"tns:PopulationInfectionAndImmunityCensus\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AbioticEcosystem\">
    <xs:sequence>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"homes\" nillable=\"true\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"schools\" nillable=\"true\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"workplaces\" nillable=\"true\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"abioticEcosystemPartCensus\">
    <xs:sequence>
      <xs:element name=\"abioticEcosystemElementID\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"LibraryItem\">
    <xs:sequence>
      <xs:element name=\"base_type\" type=\"xs:string\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SimulatorTimeRange\">
    <xs:sequence>
      <xs:element name=\"lowerBound\" type=\"xs:nonNegativeInteger\"/>
      <xs:element name=\"upperBound\" type=\"xs:nonNegativeInteger\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ContaminatedThingCensusDataCell\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"ageRange\" type=\"tns:AgeRange\"/>
      <xs:element minOccurs=\"0\" name=\"gender\" type=\"tns:Gender\"/>
      <xs:element name=\"fractionContaminated\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"SensitivityAnalysisResult\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"AbioticEcosystemElementCensusDescription\">
    <xs:sequence>
      <xs:element name=\"abioticElementID\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"characteristics\" nillable=\"true\" type=\"xs:token\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"TreatmentEfficacyValueType\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"ServiceResult\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"xs:string\"/>
      <xs:element name=\"URL\" type=\"xs:anyURI\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"TimeDefinition\">
    <xs:sequence>
      <xs:element name=\"simulatorTime\" type=\"xs:int\"/>
      <xs:element minOccurs=\"0\" name=\"dateTime\" type=\"xs:dateTime\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"ExpectedUtility\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"VaccinationEfficacyValue\">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name=\"VaccineContraindications\">
    <xs:sequence>
      <xs:element minOccurs=\"0\" name=\"infants\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"preschoolers\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"schoolAgeChildren\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"youngAdults\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"olderAdults\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"elderly\" type=\"xs:boolean\"/>
      <xs:element minOccurs=\"0\" name=\"pregnantAdultsRestricted\" type=\"xs:boolean\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"CompartmentalModelPopulationAndEnvironmentCensus\">
    <xs:sequence>
      <xs:element maxOccurs=\"unbounded\" name=\"bioticEcosystemParts\" type=\"tns:PopulationInfectionAndImmunityCensusData\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"abioticEcosystemParts\" type=\"tns:abioticEcosystemPartCensus\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"AgeGroupEfficacy\">
    <xs:sequence>
      <xs:element name=\"ageRange\" type=\"tns:AgeRange\"/>
      <xs:element name=\"vaccineEfficacy\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"PopulationStrataArray\">
    <xs:sequence>
      <xs:element name=\"description\" type=\"tns:PopulationStrataDefinition\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"values\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"FractionOfThingContaminated\">
    <xs:sequence>
      <xs:element name=\"abioticEcosystemElement\" type=\"tns:AbioticEcosystemEnum\"/>
      <xs:element name=\"fraction\" type=\"xs:double\"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name=\"PopulationCensusDescription\">
    <xs:sequence>
      <xs:element name=\"populationSpecies\" type=\"xs:string\"/>
      <xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"characteristics\" nillable=\"true\" type=\"xs:token\"/>
      <xs:element maxOccurs=\"unbounded\" name=\"locations\" type=\"tns:Location\"/>
    </xs:sequence>
  </xs:complexType>
<xs:simpleType name=\"ApolloSoftwareType\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"simulator\"/>
      <xs:enumeration value=\"visualizer\"/>
      <xs:enumeration value=\"syntheticPopulationGenerator\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"TimeStepUnit\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"year\"/>
      <xs:enumeration value=\"month\"/>
      <xs:enumeration value=\"day\"/>
      <xs:enumeration value=\"hour\"/>
      <xs:enumeration value=\"minute\"/>
      <xs:enumeration value=\"second\"/>
      <xs:enumeration value=\"millisecond\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"UnitOfMeasure\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"dollars\"/>
      <xs:enumeration value=\"euros\"/>
      <xs:enumeration value=\"weight_in_pounds\"/>
      <xs:enumeration value=\"weight_in_kilograms\"/>
      <xs:enumeration value=\"seconds\"/>
      <xs:enumeration value=\"minutes\"/>
      <xs:enumeration value=\"hours\"/>
      <xs:enumeration value=\"days\"/>
      <xs:enumeration value=\"weeks\"/>
      <xs:enumeration value=\"months\"/>
      <xs:enumeration value=\"years\"/>
      <xs:enumeration value=\"percent\"/>
      <xs:enumeration value=\"meters\"/>
      <xs:enumeration value=\"inches\"/>
      <xs:enumeration value=\"miles\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"FacilityEnum\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"preschool\"/>
      <xs:enumeration value=\"primarySchool\"/>
      <xs:enumeration value=\"secondarySchool\"/>
      <xs:enumeration value=\"workplace\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"Gender\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"M\"/>
      <xs:enumeration value=\"F\"/>
      <xs:enumeration value=\"U\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"DiseaseOutcome\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"asymptomatic\"/>
      <xs:enumeration value=\"symptomatic\"/>
      <xs:enumeration value=\"severely symptomatic\"/>
      <xs:enumeration value=\"hospitalization\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"InfectionState\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"susceptible\"/>
      <xs:enumeration value=\"exposed\"/>
      <xs:enumeration value=\"infectious\"/>
      <xs:enumeration value=\"recovered\"/>
      <xs:enumeration value=\"immuneAndActsLikeImmune\"/>
      <xs:enumeration value=\"immuneButActsLikeNotImmune\"/>
      <xs:enumeration value=\"newly_sick\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"TreatmentState\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"treated\"/>
      <xs:enumeration value=\"not_treated\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"AbioticEcosystemEnum\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"preschool\"/>
      <xs:enumeration value=\"primarySchool\"/>
      <xs:enumeration value=\"secondarySchool\"/>
      <xs:enumeration value=\"workplace\"/>
      <xs:enumeration value=\"pigFarm\"/>
      <xs:enumeration value=\"chickenFarm\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"VaccinationPreventableOutcome\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"infection\"/>
      <xs:enumeration value=\"infectiousness\"/>
      <xs:enumeration value=\"sickness requiring medical attention\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"SchoolClosureTargetFacilities\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"all\"/>
      <xs:enumeration value=\"individual\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"TargetPopulationDefinitionEnum\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"household_member_of_infant\"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name=\"MethodCallStatusEnum\">
    <xs:restriction base=\"xs:string\">
      <xs:enumeration value=\"exiting\"/>
      <xs:enumeration value=\"held\"/>
      <xs:enumeration value=\"queued\"/>
      <xs:enumeration value=\"running\"/>
      <xs:enumeration value=\"moving\"/>
      <xs:enumeration value=\"waiting\"/>
      <xs:enumeration value=\"completed\"/>
      <xs:enumeration value=\"failed\"/>
      <xs:enumeration value=\"unauthorized\"/>
      <xs:enumeration value=\"authentication_failure\"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
<xs:schema targetNamespace=\"http://service.apollo.pitt.edu/translatorservice/v2_0/\" version=\"1.0\" xmlns:ns1=\"http://types.apollo.pitt.edu/v2_0/\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
<xs:import namespace=\"http://types.apollo.pitt.edu/v2_0/\"/>
<xs:element name=\"translateRunSimulationMessage\">
    <xs:complexType>
      <xs:sequence>
        <xs:element name=\"runSimulationMessage\" type=\"ns1:RunSimulationMessage\"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name=\"translateRunSimulationMessageResponse\">
    <xs:complexType>
      <xs:sequence>
        <xs:element name=\"methodCallStatus\" type=\"ns1:MethodCallStatus\"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
  </wsdl:types>
  <wsdl:message name=\"translateRunSimulationMessageResponse\">
    <wsdl:part element=\"tns:translateRunSimulationMessageResponse\" name=\"parameters\">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name=\"translateRunSimulationMessage\">
    <wsdl:part element=\"tns:translateRunSimulationMessage\" name=\"parameters\">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name=\"TranslatorServiceEI\">
    <wsdl:operation name=\"translateRunSimulationMessage\">
      <wsdl:input message=\"tns:translateRunSimulationMessage\" name=\"translateRunSimulationMessage\">
    </wsdl:input>
      <wsdl:output message=\"tns:translateRunSimulationMessageResponse\" name=\"translateRunSimulationMessageResponse\">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name=\"TranslatorService_v2.0SoapBinding\" type=\"tns:TranslatorServiceEI\">
    <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <wsdl:operation name=\"translateRunSimulationMessage\">
      <soap:operation soapAction=\"http://service.apollo.pitt.edu/translatorservice/v2_0/translateRunSimulationMessage\" style=\"document\"/>
      <wsdl:input name=\"translateRunSimulationMessage\">
        <soap:body use=\"literal\"/>
      </wsdl:input>
      <wsdl:output name=\"translateRunSimulationMessageResponse\">
        <soap:body use=\"literal\"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name=\"TranslatorService_v2.0\">
    <wsdl:port binding=\"tns:TranslatorService_v2.0SoapBinding\" name=\"TranslatorServiceEndpoint\">
      <soap:address location=\"http://research.rods.pitt.edu/translatorservice2.0/services/translatorservice\"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/translatorservice2.0/services/translatorservice', **kw):
        ServiceSOAPBinding.__init__(self, post)
        if kw.has_key('impl'):
            self.impl = kw['impl']
        self.auth_method_name = None
        if kw.has_key('auth_method_name'):
            self.auth_method_name = kw['auth_method_name']
    def authorize(self, auth_info, post, action):
        if self.auth_method_name and hasattr(self.impl, self.auth_method_name):
            return getattr(self.impl, self.auth_method_name)(auth_info, post, action)
        else:
            return 1

    def soap_translateRunSimulationMessage(self, ps):
        self.request = ps.Parse(translateRunSimulationMessage.typecode)
        parameters = self.request._runSimulationMessage

        # If we have an implementation object use it
        if hasattr(self,'impl'):
            parameters = self.impl.translateRunSimulationMessage(parameters)

        result = translateRunSimulationMessageResponse()
        # If we have an implementation object, copy the result 
        if hasattr(self,'impl'):
            result._methodCallStatus = parameters
        return result

    soapAction['http://service.apollo.pitt.edu/translatorservice/v2_0/translateRunSimulationMessage'] = 'soap_translateRunSimulationMessage'
    root[(translateRunSimulationMessage.typecode.nspname,translateRunSimulationMessage.typecode.pname)] = 'soap_translateRunSimulationMessage'

